# Generated by Django 4.2.6 on 2023-10-14 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_region_alter_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(default=users.utils.fields.expires_default)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tokens',
            },
        ),
    ]
