# Generated by Django 4.2.6 on 2023-10-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dispatch_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
