# Generated by Django 4.2.6 on 2023-10-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='response_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_time',
            field=models.TimeField(null=True),
        ),
    ]
