# Generated by Django 4.2.6 on 2023-10-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_option_response_time_answer_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='started_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='started_date',
            field=models.DateField(null=True),
        ),
    ]
