# Generated by Django 4.2.6 on 2023-10-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_answer_option_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='finished_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='started_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='started_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='finished_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='started_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
