# Generated by Django 4.2.6 on 2023-10-14 19:47

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_specialquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct', models.BooleanField(default=False, verbose_name=main.models.Question)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_option_question', to='main.specialquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('response_time', models.TimeField(null=True)),
                ('time_delta', models.CharField(max_length=20)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_answer_option', to='main.specialquestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_answer_question', to='main.specialquestion')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_answer_student', to='main.student')),
            ],
        ),
    ]
