# Generated by Django 4.2.6 on 2023-10-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_science_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='specialquestion',
            name='science',
        ),
        migrations.AddField(
            model_name='answer',
            name='time_delta',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SpecialAnswer',
        ),
        migrations.DeleteModel(
            name='SpecialOption',
        ),
        migrations.DeleteModel(
            name='SpecialQuestion',
        ),
    ]
